### ISSUE TITLE
npm run dev 启动后页面报错

### ISSUE THREAD

**Issue by a4li** [jeryqwq/ProApplication#1]
error - ./packages/components/src/index.tsx:10:0-32
Module not found: Error: [CaseSensitivePathsPlugin] `/Users/chenlin/Documents/GitHub/ProApplication/packages/components/src/VisCrud/index.tsx` does not match the corresponding path on disk `VisCRUD`
error - ./src/pages/Table/index.tsx:14:35-42
export 'VisCRUD' (imported as 'VisCRUD') was not found in '@vis/components' (possible exports: Condition, ContextMenu, DragLayoutResize, Marquee, VisHeader, Workspace, useContextMenu)

**Comment by jeryqwq** [comment]
把ProApplication/packages/components/src/VisCRUD 文件名 /VisCrud， 估计是我git没把大小谢冲突打开

**Comment by jeryqwq** [comment]
修复了，再啦下
