### ISSUE TITLE
antd降为4.x好像不行

### ISSUE THREAD

**Issue by chumai1984** [jeryqwq/ProApplication#5]
改antd版本为4.22.2,项目pnpm i 报错;
![image](https://user-images.githubusercontent.com/17866427/220375453-f2aaf1a5-2c19-4d15-8c71-95747f5846ad.png)

**Comment by jeryqwq** [comment]
@chumai1984  是的，特意把所有的都升级新版了，包括dumi,umi,antd，也适配了新版的特性， 可以试试把umi配置里面ant相关的去掉试试

**Comment by chumai1984** [comment]
修改了一些配置,可以支持antd4.x了˜
