### ISSUE TITLE
页面报错问题

### ISSUE THREAD

**Issue by gyt95** [jeryqwq/ProApplication#6]
1.点击菜单栏-微前端-模版，提示 Unhandled Rejection (TypeError): Failed to fetch，如图：

![image](https://user-images.githubusercontent.com/23090676/222682490-daefe938-9e07-460d-8946-3df94b6d73e8.png)

2.部分按钮点击后提示 ReferenceError: setCollapse is not defined，如图：

![1677835340611](https://user-images.githubusercontent.com/23090676/222682309-cd51f944-2e72-45a0-8c35-4fe61900a424.png)

**Comment by jeryqwq** [comment]
1. 微前端dev模式下，你的子应用肯定是要先跑起来的
2.  已修复

**Comment by gyt95** [comment]
> 1. 微前端dev模式下，你的子应用肯定是要先跑起来的，不然无法加载子应用资源。
> 
> `npm run dev-project` 选中你要跑的子应用，跑起来后主应用就可以打开了
> 
> 2.  已修复

但问题是我有先执行这个步骤，选了template的，也能单独打开这个微应用，但是我在基座这里点击进入的时候依然报错

**Comment by jeryqwq** [comment]
子应用的端口是http://127.0.0.1:7777吗

**Comment by jeryqwq** [comment]
子应用端口配置错了，尴尬😅，修复了

**Comment by gyt95** [comment]
ok，现在可以了
